name: customer_data_model
version: '1.0'
config-version: 2

profile: default

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  customer_data_model:
    staging:
      +materialized: incremental
      +schema: stg
    marts:
      +materialized: incremental
      +schema: mart
    metrics:
      +enabled: true

# Optional: You can define tests, snapshots, seeds, and analysis if needed
seeds:
  customer_data_model:
    +schema: seed
    +quote_columns: false



tests:
  +severity: error
  +store_failures: true

# Optional: if using on-run-start or end hooks
on-run-start:
  - "select 'Starting customer data model build'"

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"

