{{ config(
    materialized='table' )
}}

WITH source_data AS (
    SELECT 
        CC_CALL_CENTER_SK	AS CALL_CENTER_SK,
        CC_CALL_CENTER_ID	AS CALL_CENTER_ID,
        CC_REC_START_DATE	AS REC_START_DATE,
        CC_REC_END_DATE	AS REC_END_DATE,
        CC_CLOSED_DATE_SK	AS CLOSED_DATE_SK,
        CC_OPEN_DATE_SK	AS OPEN_DATE_SK,
        CC_NAME	AS NAME,
        CC_CLASS	AS CLASS,
        CC_EMPLOYEES	AS EMPLOYEES,
        CC_SQ_FT	AS SQ_FT,
        CC_HOURS	AS HOURS,
        CC_MANAGER	AS MANAGER,
        CC_MKT_ID	AS MKT_ID,
        CC_MKT_CLASS	AS MKT_CLASS,
        CC_MKT_DESC	AS MKT_DESC,
        CC_MARKET_MANAGER	AS MARKET_MANAGER,
        CC_DIVISION	AS DIVISION,
        CC_DIVISION_NAME	AS DIVISION_NAME,
        CC_COMPANY	AS COMPANY,
        CC_COMPANY_NAME	AS COMPANY_NAME,
        CC_STREET_NUMBER	AS STREET_NUMBER,
        CC_STREET_NAME	AS STREET_NAME,
        CC_STREET_TYPE	AS STREET_TYPE,
        CC_SUITE_NUMBER	AS SUITE_NUMBER,
        CC_CITY	AS CITY,
        CC_COUNTY	AS COUNTY,
        CC_STATE	AS STATE,
        CC_ZIP	AS ZIP,
        CC_COUNTRY	AS COUNTRY,
        CC_GMT_OFFSET	AS GMT_OFFSET,
        CC_TAX_PERCENTAGE	AS TAX_PERCENTAGE
    FROM {{ source('TPCDS_SF10TCL', 'CALL_CENTER') }}
)

SELECT
    *
    {{add_current_timestamp()}}
FROM source_data
 