version: 2

models:
  - name: dim_customer
    description: Dimension table for customer core information.
    columns:
      - name: c_customer_sk
        description: Primary key for customer dimension
        tests:
          - unique
          - not_null
      - name: c_customer_id
        description: Natural key from source system
        tests:
          - not_null
      - name: c_email_address
        description: Customer's email address
        tests:
          - not_null

  - name: dim_customer_address
    description: Customer address dimension
    columns:
      - name: ca_address_sk
        tests:
          - unique
          - not_null

  - name: dim_customer_demographics
    description: Customer demographic attributes
    columns:
      - name: cd_demo_sk
        tests:
          - unique
          - not_null

  - name: fact_catalog_sales
    description: Sales fact table from catalog channel
    columns:
      - name: cs_order_number
        tests:
          - not_null
      - name: cs_customer_sk
        tests:
          - relationships:
              to: ref('dim_customer')
              field: c_customer_sk
      - name: cs_item_sk
        tests:
          - not_null

  - name: fact_catalog_returns
    description: Catalog returns fact table
    columns:
      - name: cr_order_number
        tests:
          - not_null
      - name: cr_returning_customer_sk
        tests:
          - relationships:
              to: ref('dim_customer')
              field: c_customer_sk
