version: 2

models:
  - name: dim_customer
    description: Dimension table for customer core information.
    columns:
      - name: CUSTOMER_SK
        description: Primary key for customer dimension
        tests:
          - unique
          - not_null
      - name: CUSTOMER_ID
        description: Natural key from source system
        tests:
          - not_null
      - name: EMAIL_ADDRESS
        description: Customer's email address
        tests:
          - not_null

  - name: dim_customer_addr
    description: Customer address dimension
    columns:
      - name: ADDRESS_SK
        tests:
          - unique
          - not_null

  - name: dim_customer_demo
    description: Customer demographic attributes
    columns:
      - name: demo_sk
        tests:
          - unique
          - not_null

  - name: fact_catalog_sales
    description: Sales fact table from catalog channel
    columns:
      - name: order_number
        tests:
          - not_null
      - name: customer_sk
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_sk
      - name: item_sk
        tests:
          - not_null

  - name: fact_catalog_returns
    description: Catalog returns fact table
    columns:
      - name: order_number
        tests:
          - not_null
      - name: returning_customer_sk
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_sk
